apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:   # We dont need to worry about converting to base64
  MYSQL_USER: root
  MYSQL_PASSWORD: some_pass
  MYSQL_DATABASE: restful_api_go
  MYSQL_ROOT_PASSWORD: some_pass

  DB_HOST: fullstack-mysql
  DB_DRIVER: mysql
  API_SECRET: 98hbun98h 
  DB_USER: root
  DB_PASSWORD: some_pass
  DB_NAME: restful_api_go
  DB_PORT: "3306"

  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_HOST: "fullstack-redis"
  REDIS_PORT: "6379"
  ACCESS_SECRET: "testing12121" #Used when creating a JWT. It can be anything"
  REFRESH_SECRET: "testing121212"