apiVersion: apps/v1
kind: Deployment                            # Type of the kubernetes resource
metadata:
  name: fullstack-redis                     # Name of the deployment (Use this name as db host in your application)
  labels:                                   # Labels applied to this deployment
    app: fullstack-redis
spec:
  selector:
    matchLabels:                            # This deployment applies to the Pods matching the specified labels
      app: fullstack-redis
      tier: redis
  strategy:
    type: Recreate 
  replicas: 1
  template:                                 # Template for the pods in this deployment
    metadata: 
      labels:                               # labels to be applied to the pods in this deployment 
        app: fullstack-redis
        tier: redis
    spec:                                   # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: bitnami/redis:latest               # The container image
          name: redis
          imagePullPolicy: "IfNotPresent"   # Get it from dockerhub if it is not present in our machine

          envFrom:                                # Environment variables passed to the container 
          - secretRef:                            # Read environment variables from kubernetes secrets
              name: mysql-secret

          ports:
          - containerPort: 6379             # The port that the container exposes 
            name: redis
          volumeMounts:
            - mountPath: /var/lib/redis
              name: redis-persistent-storage # This name should match the name specified in `volumes.name`
      volumes:                        # A PersistentVolume is mounted as a volume to the Pod  
      - name: redis-persistent-storage 
        persistentVolumeClaim:
          claimName: redis-pv-claim

